name: (Manual) Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    uses: The-Mag-Pie/workflows/.github/workflows/deploy.yml@main
    with:
      compose-file-name: email-ads-remover.yml
      project-name: scripts
    secrets: inherit
